spring.application.name=notification-service

spring.kafka.bootstrap-servers=localhost:9092
logging.level.org.springframework.kafka=DEBUG

#email send
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=awhateshubham1573@gmail.com
#spring.mail.password=nwfuoyxlfmailmyn
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

#sms/whats up send
#twilio.accountSid=ACea997712c714175f0f5de30d7340c902
#twilio.authToken=d74dd662774d16a7935e65c3f1f01c55
#twilio.phoneNumber=+17014509921
#twilio.whatsappNumber=+14155238886